function remote_init(manufacturer, model)
	-- defining control surface items

	local items = {
                {name="User 1 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 1 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 1 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 1 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 1 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 1 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 1 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 1 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 1 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 1 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 1 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 1 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 1 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 1 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 1 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 1 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 1 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 1 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 2 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 2 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 2 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 2 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 2 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 2 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 2 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 2 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 2 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 2 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 2 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 2 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 2 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 2 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 2 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 2 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 2 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 3 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 3 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 3 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 3 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 3 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 3 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 3 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 3 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 3 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 3 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 3 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 3 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 3 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 3 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 3 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 3 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 3 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 4 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 4 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 4 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 4 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 4 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 4 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 4 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 4 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 4 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 4 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 4 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 4 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 4 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 4 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 4 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 4 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 4 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 5 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 5 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 5 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 5 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 5 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 5 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 5 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 5 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 5 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 5 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 5 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 5 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 5 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 5 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 5 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 5 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 5 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 6 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 6 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 6 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 6 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 6 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 6 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 6 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 6 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 6 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 6 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 6 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 6 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 6 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 6 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 6 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 6 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 6 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 7 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 7 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 7 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 7 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 7 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 7 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 7 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 7 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 7 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 7 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 7 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 7 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 7 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 7 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 7 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 7 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 7 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 8 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 8 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 8 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 8 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 8 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 8 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 8 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="User 8 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 8 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 8 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 8 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 8 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 8 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 8 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 8 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="User 8 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="User 8 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 1 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 2 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 3 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 4 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 5 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 6 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 7 Track 8 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 1 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 2 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 3 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 4 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 5 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 6 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 7 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 8 Knob 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 1 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 2 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 3 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 4 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 5 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 6 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 7 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 8 Knob 2", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 1 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 2 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 3 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 4 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 5 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 6 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 7 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 8 Knob 3", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 1 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 2 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 3 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 4 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 5 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 6 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 7 Fader 1", input="value", output="value", min=0, max=127},
                {name="Factory 8 Track 8 Fader 1", input="value", output="value", min=0, max=127}
	}

	remote.define_items(items)

	local inputs = {


                {pattern="B0 0D xx", name="User 1 Track 1 Knob 1"},
                {pattern="B0 0E xx", name="User 1 Track 2 Knob 1"},
                {pattern="B0 0F xx", name="User 1 Track 3 Knob 1"},
                {pattern="B0 10 xx", name="User 1 Track 4 Knob 1"},
                {pattern="B0 11 xx", name="User 1 Track 5 Knob 1"},
                {pattern="B0 12 xx", name="User 1 Track 6 Knob 1"},
                {pattern="B0 13 xx", name="User 1 Track 7 Knob 1"},
                {pattern="B0 14 xx", name="User 1 Track 8 Knob 1"},
                {pattern="B0 1D xx", name="User 1 Track 1 Knob 2"},
                {pattern="B0 1E xx", name="User 1 Track 2 Knob 2"},
                {pattern="B0 1F xx", name="User 1 Track 3 Knob 2"},
                {pattern="B0 20 xx", name="User 1 Track 4 Knob 2"},
                {pattern="B0 21 xx", name="User 1 Track 5 Knob 2"},
                {pattern="B0 22 xx", name="User 1 Track 6 Knob 2"},
                {pattern="B0 23 xx", name="User 1 Track 7 Knob 2"},
                {pattern="B0 24 xx", name="User 1 Track 8 Knob 2"},
                {pattern="B0 31 xx", name="User 1 Track 1 Knob 3"},
                {pattern="B0 32 xx", name="User 1 Track 2 Knob 3"},
                {pattern="B0 33 xx", name="User 1 Track 3 Knob 3"},
                {pattern="B0 34 xx", name="User 1 Track 4 Knob 3"},
                {pattern="B0 35 xx", name="User 1 Track 5 Knob 3"},
                {pattern="B0 36 xx", name="User 1 Track 6 Knob 3"},
                {pattern="B0 37 xx", name="User 1 Track 7 Knob 3"},
                {pattern="B0 38 xx", name="User 1 Track 8 Knob 3"},
                {pattern="B0 4D xx", name="User 1 Track 1 Fader 1"},
                {pattern="B0 4E xx", name="User 1 Track 2 Fader 1"},
                {pattern="B0 4F xx", name="User 1 Track 3 Fader 1"},
                {pattern="B0 50 xx", name="User 1 Track 4 Fader 1"},
                {pattern="B0 51 xx", name="User 1 Track 5 Fader 1"},
                {pattern="B0 52 xx", name="User 1 Track 6 Fader 1"},
                {pattern="B0 53 xx", name="User 1 Track 7 Fader 1"},
                {pattern="B0 54 xx", name="User 1 Track 8 Fader 1"},
                {pattern="B1 0D xx", name="User 2 Track 1 Knob 1"},
                {pattern="B1 0E xx", name="User 2 Track 2 Knob 1"},
                {pattern="B1 0F xx", name="User 2 Track 3 Knob 1"},
                {pattern="B1 10 xx", name="User 2 Track 4 Knob 1"},
                {pattern="B1 11 xx", name="User 2 Track 5 Knob 1"},
                {pattern="B1 12 xx", name="User 2 Track 6 Knob 1"},
                {pattern="B1 13 xx", name="User 2 Track 7 Knob 1"},
                {pattern="B1 14 xx", name="User 2 Track 8 Knob 1"},
                {pattern="B1 1D xx", name="User 2 Track 1 Knob 2"},
                {pattern="B1 1E xx", name="User 2 Track 2 Knob 2"},
                {pattern="B1 1F xx", name="User 2 Track 3 Knob 2"},
                {pattern="B1 20 xx", name="User 2 Track 4 Knob 2"},
                {pattern="B1 21 xx", name="User 2 Track 5 Knob 2"},
                {pattern="B1 22 xx", name="User 2 Track 6 Knob 2"},
                {pattern="B1 23 xx", name="User 2 Track 7 Knob 2"},
                {pattern="B1 24 xx", name="User 2 Track 8 Knob 2"},
                {pattern="B1 31 xx", name="User 2 Track 1 Knob 3"},
                {pattern="B1 32 xx", name="User 2 Track 2 Knob 3"},
                {pattern="B1 33 xx", name="User 2 Track 3 Knob 3"},
                {pattern="B1 34 xx", name="User 2 Track 4 Knob 3"},
                {pattern="B1 35 xx", name="User 2 Track 5 Knob 3"},
                {pattern="B1 36 xx", name="User 2 Track 6 Knob 3"},
                {pattern="B1 37 xx", name="User 2 Track 7 Knob 3"},
                {pattern="B1 38 xx", name="User 2 Track 8 Knob 3"},
                {pattern="B1 4D xx", name="User 2 Track 1 Fader 1"},
                {pattern="B1 4E xx", name="User 2 Track 2 Fader 1"},
                {pattern="B1 4F xx", name="User 2 Track 3 Fader 1"},
                {pattern="B1 50 xx", name="User 2 Track 4 Fader 1"},
                {pattern="B1 51 xx", name="User 2 Track 5 Fader 1"},
                {pattern="B1 52 xx", name="User 2 Track 6 Fader 1"},
                {pattern="B1 53 xx", name="User 2 Track 7 Fader 1"},
                {pattern="B1 54 xx", name="User 2 Track 8 Fader 1"},
                {pattern="B2 0D xx", name="User 3 Track 1 Knob 1"},
                {pattern="B2 0E xx", name="User 3 Track 2 Knob 1"},
                {pattern="B2 0F xx", name="User 3 Track 3 Knob 1"},
                {pattern="B2 10 xx", name="User 3 Track 4 Knob 1"},
                {pattern="B2 11 xx", name="User 3 Track 5 Knob 1"},
                {pattern="B2 12 xx", name="User 3 Track 6 Knob 1"},
                {pattern="B2 13 xx", name="User 3 Track 7 Knob 1"},
                {pattern="B2 14 xx", name="User 3 Track 8 Knob 1"},
                {pattern="B2 1D xx", name="User 3 Track 1 Knob 2"},
                {pattern="B2 1E xx", name="User 3 Track 2 Knob 2"},
                {pattern="B2 1F xx", name="User 3 Track 3 Knob 2"},
                {pattern="B2 20 xx", name="User 3 Track 4 Knob 2"},
                {pattern="B2 21 xx", name="User 3 Track 5 Knob 2"},
                {pattern="B2 22 xx", name="User 3 Track 6 Knob 2"},
                {pattern="B2 23 xx", name="User 3 Track 7 Knob 2"},
                {pattern="B2 24 xx", name="User 3 Track 8 Knob 2"},
                {pattern="B2 31 xx", name="User 3 Track 1 Knob 3"},
                {pattern="B2 32 xx", name="User 3 Track 2 Knob 3"},
                {pattern="B2 33 xx", name="User 3 Track 3 Knob 3"},
                {pattern="B2 34 xx", name="User 3 Track 4 Knob 3"},
                {pattern="B2 35 xx", name="User 3 Track 5 Knob 3"},
                {pattern="B2 36 xx", name="User 3 Track 6 Knob 3"},
                {pattern="B2 37 xx", name="User 3 Track 7 Knob 3"},
                {pattern="B2 38 xx", name="User 3 Track 8 Knob 3"},
                {pattern="B2 4D xx", name="User 3 Track 1 Fader 1"},
                {pattern="B2 4E xx", name="User 3 Track 2 Fader 1"},
                {pattern="B2 4F xx", name="User 3 Track 3 Fader 1"},
                {pattern="B2 50 xx", name="User 3 Track 4 Fader 1"},
                {pattern="B2 51 xx", name="User 3 Track 5 Fader 1"},
                {pattern="B2 52 xx", name="User 3 Track 6 Fader 1"},
                {pattern="B2 53 xx", name="User 3 Track 7 Fader 1"},
                {pattern="B2 54 xx", name="User 3 Track 8 Fader 1"},
                {pattern="B3 0D xx", name="User 4 Track 1 Knob 1"},
                {pattern="B3 0E xx", name="User 4 Track 2 Knob 1"},
                {pattern="B3 0F xx", name="User 4 Track 3 Knob 1"},
                {pattern="B3 10 xx", name="User 4 Track 4 Knob 1"},
                {pattern="B3 11 xx", name="User 4 Track 5 Knob 1"},
                {pattern="B3 12 xx", name="User 4 Track 6 Knob 1"},
                {pattern="B3 13 xx", name="User 4 Track 7 Knob 1"},
                {pattern="B3 14 xx", name="User 4 Track 8 Knob 1"},
                {pattern="B3 1D xx", name="User 4 Track 1 Knob 2"},
                {pattern="B3 1E xx", name="User 4 Track 2 Knob 2"},
                {pattern="B3 1F xx", name="User 4 Track 3 Knob 2"},
                {pattern="B3 20 xx", name="User 4 Track 4 Knob 2"},
                {pattern="B3 21 xx", name="User 4 Track 5 Knob 2"},
                {pattern="B3 22 xx", name="User 4 Track 6 Knob 2"},
                {pattern="B3 23 xx", name="User 4 Track 7 Knob 2"},
                {pattern="B3 24 xx", name="User 4 Track 8 Knob 2"},
                {pattern="B3 31 xx", name="User 4 Track 1 Knob 3"},
                {pattern="B3 32 xx", name="User 4 Track 2 Knob 3"},
                {pattern="B3 33 xx", name="User 4 Track 3 Knob 3"},
                {pattern="B3 34 xx", name="User 4 Track 4 Knob 3"},
                {pattern="B3 35 xx", name="User 4 Track 5 Knob 3"},
                {pattern="B3 36 xx", name="User 4 Track 6 Knob 3"},
                {pattern="B3 37 xx", name="User 4 Track 7 Knob 3"},
                {pattern="B3 38 xx", name="User 4 Track 8 Knob 3"},
                {pattern="B3 4D xx", name="User 4 Track 1 Fader 1"},
                {pattern="B3 4E xx", name="User 4 Track 2 Fader 1"},
                {pattern="B3 4F xx", name="User 4 Track 3 Fader 1"},
                {pattern="B3 50 xx", name="User 4 Track 4 Fader 1"},
                {pattern="B3 51 xx", name="User 4 Track 5 Fader 1"},
                {pattern="B3 52 xx", name="User 4 Track 6 Fader 1"},
                {pattern="B3 53 xx", name="User 4 Track 7 Fader 1"},
                {pattern="B3 54 xx", name="User 4 Track 8 Fader 1"},
                {pattern="B4 0D xx", name="User 5 Track 1 Knob 1"},
                {pattern="B4 0E xx", name="User 5 Track 2 Knob 1"},
                {pattern="B4 0F xx", name="User 5 Track 3 Knob 1"},
                {pattern="B4 10 xx", name="User 5 Track 4 Knob 1"},
                {pattern="B4 11 xx", name="User 5 Track 5 Knob 1"},
                {pattern="B4 12 xx", name="User 5 Track 6 Knob 1"},
                {pattern="B4 13 xx", name="User 5 Track 7 Knob 1"},
                {pattern="B4 14 xx", name="User 5 Track 8 Knob 1"},
                {pattern="B4 1D xx", name="User 5 Track 1 Knob 2"},
                {pattern="B4 1E xx", name="User 5 Track 2 Knob 2"},
                {pattern="B4 1F xx", name="User 5 Track 3 Knob 2"},
                {pattern="B4 20 xx", name="User 5 Track 4 Knob 2"},
                {pattern="B4 21 xx", name="User 5 Track 5 Knob 2"},
                {pattern="B4 22 xx", name="User 5 Track 6 Knob 2"},
                {pattern="B4 23 xx", name="User 5 Track 7 Knob 2"},
                {pattern="B4 24 xx", name="User 5 Track 8 Knob 2"},
                {pattern="B4 31 xx", name="User 5 Track 1 Knob 3"},
                {pattern="B4 32 xx", name="User 5 Track 2 Knob 3"},
                {pattern="B4 33 xx", name="User 5 Track 3 Knob 3"},
                {pattern="B4 34 xx", name="User 5 Track 4 Knob 3"},
                {pattern="B4 35 xx", name="User 5 Track 5 Knob 3"},
                {pattern="B4 36 xx", name="User 5 Track 6 Knob 3"},
                {pattern="B4 37 xx", name="User 5 Track 7 Knob 3"},
                {pattern="B4 38 xx", name="User 5 Track 8 Knob 3"},
                {pattern="B4 4D xx", name="User 5 Track 1 Fader 1"},
                {pattern="B4 4E xx", name="User 5 Track 2 Fader 1"},
                {pattern="B4 4F xx", name="User 5 Track 3 Fader 1"},
                {pattern="B4 50 xx", name="User 5 Track 4 Fader 1"},
                {pattern="B4 51 xx", name="User 5 Track 5 Fader 1"},
                {pattern="B4 52 xx", name="User 5 Track 6 Fader 1"},
                {pattern="B4 53 xx", name="User 5 Track 7 Fader 1"},
                {pattern="B4 54 xx", name="User 5 Track 8 Fader 1"},
                {pattern="B5 0D xx", name="User 6 Track 1 Knob 1"},
                {pattern="B5 0E xx", name="User 6 Track 2 Knob 1"},
                {pattern="B5 0F xx", name="User 6 Track 3 Knob 1"},
                {pattern="B5 10 xx", name="User 6 Track 4 Knob 1"},
                {pattern="B5 11 xx", name="User 6 Track 5 Knob 1"},
                {pattern="B5 12 xx", name="User 6 Track 6 Knob 1"},
                {pattern="B5 13 xx", name="User 6 Track 7 Knob 1"},
                {pattern="B5 14 xx", name="User 6 Track 8 Knob 1"},
                {pattern="B5 1D xx", name="User 6 Track 1 Knob 2"},
                {pattern="B5 1E xx", name="User 6 Track 2 Knob 2"},
                {pattern="B5 1F xx", name="User 6 Track 3 Knob 2"},
                {pattern="B5 20 xx", name="User 6 Track 4 Knob 2"},
                {pattern="B5 21 xx", name="User 6 Track 5 Knob 2"},
                {pattern="B5 22 xx", name="User 6 Track 6 Knob 2"},
                {pattern="B5 23 xx", name="User 6 Track 7 Knob 2"},
                {pattern="B5 24 xx", name="User 6 Track 8 Knob 2"},
                {pattern="B5 31 xx", name="User 6 Track 1 Knob 3"},
                {pattern="B5 32 xx", name="User 6 Track 2 Knob 3"},
                {pattern="B5 33 xx", name="User 6 Track 3 Knob 3"},
                {pattern="B5 34 xx", name="User 6 Track 4 Knob 3"},
                {pattern="B5 35 xx", name="User 6 Track 5 Knob 3"},
                {pattern="B5 36 xx", name="User 6 Track 6 Knob 3"},
                {pattern="B5 37 xx", name="User 6 Track 7 Knob 3"},
                {pattern="B5 38 xx", name="User 6 Track 8 Knob 3"},
                {pattern="B5 4D xx", name="User 6 Track 1 Fader 1"},
                {pattern="B5 4E xx", name="User 6 Track 2 Fader 1"},
                {pattern="B5 4F xx", name="User 6 Track 3 Fader 1"},
                {pattern="B5 50 xx", name="User 6 Track 4 Fader 1"},
                {pattern="B5 51 xx", name="User 6 Track 5 Fader 1"},
                {pattern="B5 52 xx", name="User 6 Track 6 Fader 1"},
                {pattern="B5 53 xx", name="User 6 Track 7 Fader 1"},
                {pattern="B5 54 xx", name="User 6 Track 8 Fader 1"},
                {pattern="B6 0D xx", name="User 7 Track 1 Knob 1"},
                {pattern="B6 0E xx", name="User 7 Track 2 Knob 1"},
                {pattern="B6 0F xx", name="User 7 Track 3 Knob 1"},
                {pattern="B6 10 xx", name="User 7 Track 4 Knob 1"},
                {pattern="B6 11 xx", name="User 7 Track 5 Knob 1"},
                {pattern="B6 12 xx", name="User 7 Track 6 Knob 1"},
                {pattern="B6 13 xx", name="User 7 Track 7 Knob 1"},
                {pattern="B6 14 xx", name="User 7 Track 8 Knob 1"},
                {pattern="B6 1D xx", name="User 7 Track 1 Knob 2"},
                {pattern="B6 1E xx", name="User 7 Track 2 Knob 2"},
                {pattern="B6 1F xx", name="User 7 Track 3 Knob 2"},
                {pattern="B6 20 xx", name="User 7 Track 4 Knob 2"},
                {pattern="B6 21 xx", name="User 7 Track 5 Knob 2"},
                {pattern="B6 22 xx", name="User 7 Track 6 Knob 2"},
                {pattern="B6 23 xx", name="User 7 Track 7 Knob 2"},
                {pattern="B6 24 xx", name="User 7 Track 8 Knob 2"},
                {pattern="B6 31 xx", name="User 7 Track 1 Knob 3"},
                {pattern="B6 32 xx", name="User 7 Track 2 Knob 3"},
                {pattern="B6 33 xx", name="User 7 Track 3 Knob 3"},
                {pattern="B6 34 xx", name="User 7 Track 4 Knob 3"},
                {pattern="B6 35 xx", name="User 7 Track 5 Knob 3"},
                {pattern="B6 36 xx", name="User 7 Track 6 Knob 3"},
                {pattern="B6 37 xx", name="User 7 Track 7 Knob 3"},
                {pattern="B6 38 xx", name="User 7 Track 8 Knob 3"},
                {pattern="B6 4D xx", name="User 7 Track 1 Fader 1"},
                {pattern="B6 4E xx", name="User 7 Track 2 Fader 1"},
                {pattern="B6 4F xx", name="User 7 Track 3 Fader 1"},
                {pattern="B6 50 xx", name="User 7 Track 4 Fader 1"},
                {pattern="B6 51 xx", name="User 7 Track 5 Fader 1"},
                {pattern="B6 52 xx", name="User 7 Track 6 Fader 1"},
                {pattern="B6 53 xx", name="User 7 Track 7 Fader 1"},
                {pattern="B6 54 xx", name="User 7 Track 8 Fader 1"},
                {pattern="B7 0D xx", name="User 8 Track 1 Knob 1"},
                {pattern="B7 0E xx", name="User 8 Track 2 Knob 1"},
                {pattern="B7 0F xx", name="User 8 Track 3 Knob 1"},
                {pattern="B7 10 xx", name="User 8 Track 4 Knob 1"},
                {pattern="B7 11 xx", name="User 8 Track 5 Knob 1"},
                {pattern="B7 12 xx", name="User 8 Track 6 Knob 1"},
                {pattern="B7 13 xx", name="User 8 Track 7 Knob 1"},
                {pattern="B7 14 xx", name="User 8 Track 8 Knob 1"},
                {pattern="B7 1D xx", name="User 8 Track 1 Knob 2"},
                {pattern="B7 1E xx", name="User 8 Track 2 Knob 2"},
                {pattern="B7 1F xx", name="User 8 Track 3 Knob 2"},
                {pattern="B7 20 xx", name="User 8 Track 4 Knob 2"},
                {pattern="B7 21 xx", name="User 8 Track 5 Knob 2"},
                {pattern="B7 22 xx", name="User 8 Track 6 Knob 2"},
                {pattern="B7 23 xx", name="User 8 Track 7 Knob 2"},
                {pattern="B7 24 xx", name="User 8 Track 8 Knob 2"},
                {pattern="B7 31 xx", name="User 8 Track 1 Knob 3"},
                {pattern="B7 32 xx", name="User 8 Track 2 Knob 3"},
                {pattern="B7 33 xx", name="User 8 Track 3 Knob 3"},
                {pattern="B7 34 xx", name="User 8 Track 4 Knob 3"},
                {pattern="B7 35 xx", name="User 8 Track 5 Knob 3"},
                {pattern="B7 36 xx", name="User 8 Track 6 Knob 3"},
                {pattern="B7 37 xx", name="User 8 Track 7 Knob 3"},
                {pattern="B7 38 xx", name="User 8 Track 8 Knob 3"},
                {pattern="B7 4D xx", name="User 8 Track 1 Fader 1"},
                {pattern="B7 4E xx", name="User 8 Track 2 Fader 1"},
                {pattern="B7 4F xx", name="User 8 Track 3 Fader 1"},
                {pattern="B7 50 xx", name="User 8 Track 4 Fader 1"},
                {pattern="B7 51 xx", name="User 8 Track 5 Fader 1"},
                {pattern="B7 52 xx", name="User 8 Track 6 Fader 1"},
                {pattern="B7 53 xx", name="User 8 Track 7 Fader 1"},
                {pattern="B7 54 xx", name="User 8 Track 8 Fader 1"},
                {pattern="B8 0D xx", name="Factory 1 Track 1 Knob 1"},
                {pattern="B8 0E xx", name="Factory 1 Track 2 Knob 1"},
                {pattern="B8 0F xx", name="Factory 1 Track 3 Knob 1"},
                {pattern="B8 10 xx", name="Factory 1 Track 4 Knob 1"},
                {pattern="B8 11 xx", name="Factory 1 Track 5 Knob 1"},
                {pattern="B8 12 xx", name="Factory 1 Track 6 Knob 1"},
                {pattern="B8 13 xx", name="Factory 1 Track 7 Knob 1"},
                {pattern="B8 14 xx", name="Factory 1 Track 8 Knob 1"},
                {pattern="B8 1D xx", name="Factory 1 Track 1 Knob 2"},
                {pattern="B8 1E xx", name="Factory 1 Track 2 Knob 2"},
                {pattern="B8 1F xx", name="Factory 1 Track 3 Knob 2"},
                {pattern="B8 20 xx", name="Factory 1 Track 4 Knob 2"},
                {pattern="B8 21 xx", name="Factory 1 Track 5 Knob 2"},
                {pattern="B8 22 xx", name="Factory 1 Track 6 Knob 2"},
                {pattern="B8 23 xx", name="Factory 1 Track 7 Knob 2"},
                {pattern="B8 24 xx", name="Factory 1 Track 8 Knob 2"},
                {pattern="B8 31 xx", name="Factory 1 Track 1 Knob 3"},
                {pattern="B8 32 xx", name="Factory 1 Track 2 Knob 3"},
                {pattern="B8 33 xx", name="Factory 1 Track 3 Knob 3"},
                {pattern="B8 34 xx", name="Factory 1 Track 4 Knob 3"},
                {pattern="B8 35 xx", name="Factory 1 Track 5 Knob 3"},
                {pattern="B8 36 xx", name="Factory 1 Track 6 Knob 3"},
                {pattern="B8 37 xx", name="Factory 1 Track 7 Knob 3"},
                {pattern="B8 38 xx", name="Factory 1 Track 8 Knob 3"},
                {pattern="B8 4D xx", name="Factory 1 Track 1 Fader 1"},
                {pattern="B8 4E xx", name="Factory 1 Track 2 Fader 1"},
                {pattern="B8 4F xx", name="Factory 1 Track 3 Fader 1"},
                {pattern="B8 50 xx", name="Factory 1 Track 4 Fader 1"},
                {pattern="B8 51 xx", name="Factory 1 Track 5 Fader 1"},
                {pattern="B8 52 xx", name="Factory 1 Track 6 Fader 1"},
                {pattern="B8 53 xx", name="Factory 1 Track 7 Fader 1"},
                {pattern="B8 54 xx", name="Factory 1 Track 8 Fader 1"},
                {pattern="B9 0D xx", name="Factory 2 Track 1 Knob 1"},
                {pattern="B9 0E xx", name="Factory 2 Track 2 Knob 1"},
                {pattern="B9 0F xx", name="Factory 2 Track 3 Knob 1"},
                {pattern="B9 10 xx", name="Factory 2 Track 4 Knob 1"},
                {pattern="B9 11 xx", name="Factory 2 Track 5 Knob 1"},
                {pattern="B9 12 xx", name="Factory 2 Track 6 Knob 1"},
                {pattern="B9 13 xx", name="Factory 2 Track 7 Knob 1"},
                {pattern="B9 14 xx", name="Factory 2 Track 8 Knob 1"},
                {pattern="B9 1D xx", name="Factory 2 Track 1 Knob 2"},
                {pattern="B9 1E xx", name="Factory 2 Track 2 Knob 2"},
                {pattern="B9 1F xx", name="Factory 2 Track 3 Knob 2"},
                {pattern="B9 20 xx", name="Factory 2 Track 4 Knob 2"},
                {pattern="B9 21 xx", name="Factory 2 Track 5 Knob 2"},
                {pattern="B9 22 xx", name="Factory 2 Track 6 Knob 2"},
                {pattern="B9 23 xx", name="Factory 2 Track 7 Knob 2"},
                {pattern="B9 24 xx", name="Factory 2 Track 8 Knob 2"},
                {pattern="B9 31 xx", name="Factory 2 Track 1 Knob 3"},
                {pattern="B9 32 xx", name="Factory 2 Track 2 Knob 3"},
                {pattern="B9 33 xx", name="Factory 2 Track 3 Knob 3"},
                {pattern="B9 34 xx", name="Factory 2 Track 4 Knob 3"},
                {pattern="B9 35 xx", name="Factory 2 Track 5 Knob 3"},
                {pattern="B9 36 xx", name="Factory 2 Track 6 Knob 3"},
                {pattern="B9 37 xx", name="Factory 2 Track 7 Knob 3"},
                {pattern="B9 38 xx", name="Factory 2 Track 8 Knob 3"},
                {pattern="B9 4D xx", name="Factory 2 Track 1 Fader 1"},
                {pattern="B9 4E xx", name="Factory 2 Track 2 Fader 1"},
                {pattern="B9 4F xx", name="Factory 2 Track 3 Fader 1"},
                {pattern="B9 50 xx", name="Factory 2 Track 4 Fader 1"},
                {pattern="B9 51 xx", name="Factory 2 Track 5 Fader 1"},
                {pattern="B9 52 xx", name="Factory 2 Track 6 Fader 1"},
                {pattern="B9 53 xx", name="Factory 2 Track 7 Fader 1"},
                {pattern="B9 54 xx", name="Factory 2 Track 8 Fader 1"},
                {pattern="BA 0D xx", name="Factory 3 Track 1 Knob 1"},
                {pattern="BA 0E xx", name="Factory 3 Track 2 Knob 1"},
                {pattern="BA 0F xx", name="Factory 3 Track 3 Knob 1"},
                {pattern="BA 10 xx", name="Factory 3 Track 4 Knob 1"},
                {pattern="BA 11 xx", name="Factory 3 Track 5 Knob 1"},
                {pattern="BA 12 xx", name="Factory 3 Track 6 Knob 1"},
                {pattern="BA 13 xx", name="Factory 3 Track 7 Knob 1"},
                {pattern="BA 14 xx", name="Factory 3 Track 8 Knob 1"},
                {pattern="BA 1D xx", name="Factory 3 Track 1 Knob 2"},
                {pattern="BA 1E xx", name="Factory 3 Track 2 Knob 2"},
                {pattern="BA 1F xx", name="Factory 3 Track 3 Knob 2"},
                {pattern="BA 20 xx", name="Factory 3 Track 4 Knob 2"},
                {pattern="BA 21 xx", name="Factory 3 Track 5 Knob 2"},
                {pattern="BA 22 xx", name="Factory 3 Track 6 Knob 2"},
                {pattern="BA 23 xx", name="Factory 3 Track 7 Knob 2"},
                {pattern="BA 24 xx", name="Factory 3 Track 8 Knob 2"},
                {pattern="BA 31 xx", name="Factory 3 Track 1 Knob 3"},
                {pattern="BA 32 xx", name="Factory 3 Track 2 Knob 3"},
                {pattern="BA 33 xx", name="Factory 3 Track 3 Knob 3"},
                {pattern="BA 34 xx", name="Factory 3 Track 4 Knob 3"},
                {pattern="BA 35 xx", name="Factory 3 Track 5 Knob 3"},
                {pattern="BA 36 xx", name="Factory 3 Track 6 Knob 3"},
                {pattern="BA 37 xx", name="Factory 3 Track 7 Knob 3"},
                {pattern="BA 38 xx", name="Factory 3 Track 8 Knob 3"},
                {pattern="BA 4D xx", name="Factory 3 Track 1 Fader 1"},
                {pattern="BA 4E xx", name="Factory 3 Track 2 Fader 1"},
                {pattern="BA 4F xx", name="Factory 3 Track 3 Fader 1"},
                {pattern="BA 50 xx", name="Factory 3 Track 4 Fader 1"},
                {pattern="BA 51 xx", name="Factory 3 Track 5 Fader 1"},
                {pattern="BA 52 xx", name="Factory 3 Track 6 Fader 1"},
                {pattern="BA 53 xx", name="Factory 3 Track 7 Fader 1"},
                {pattern="BA 54 xx", name="Factory 3 Track 8 Fader 1"},
                {pattern="BB 0D xx", name="Factory 4 Track 1 Knob 1"},
                {pattern="BB 0E xx", name="Factory 4 Track 2 Knob 1"},
                {pattern="BB 0F xx", name="Factory 4 Track 3 Knob 1"},
                {pattern="BB 10 xx", name="Factory 4 Track 4 Knob 1"},
                {pattern="BB 11 xx", name="Factory 4 Track 5 Knob 1"},
                {pattern="BB 12 xx", name="Factory 4 Track 6 Knob 1"},
                {pattern="BB 13 xx", name="Factory 4 Track 7 Knob 1"},
                {pattern="BB 14 xx", name="Factory 4 Track 8 Knob 1"},
                {pattern="BB 1D xx", name="Factory 4 Track 1 Knob 2"},
                {pattern="BB 1E xx", name="Factory 4 Track 2 Knob 2"},
                {pattern="BB 1F xx", name="Factory 4 Track 3 Knob 2"},
                {pattern="BB 20 xx", name="Factory 4 Track 4 Knob 2"},
                {pattern="BB 21 xx", name="Factory 4 Track 5 Knob 2"},
                {pattern="BB 22 xx", name="Factory 4 Track 6 Knob 2"},
                {pattern="BB 23 xx", name="Factory 4 Track 7 Knob 2"},
                {pattern="BB 24 xx", name="Factory 4 Track 8 Knob 2"},
                {pattern="BB 31 xx", name="Factory 4 Track 1 Knob 3"},
                {pattern="BB 32 xx", name="Factory 4 Track 2 Knob 3"},
                {pattern="BB 33 xx", name="Factory 4 Track 3 Knob 3"},
                {pattern="BB 34 xx", name="Factory 4 Track 4 Knob 3"},
                {pattern="BB 35 xx", name="Factory 4 Track 5 Knob 3"},
                {pattern="BB 36 xx", name="Factory 4 Track 6 Knob 3"},
                {pattern="BB 37 xx", name="Factory 4 Track 7 Knob 3"},
                {pattern="BB 38 xx", name="Factory 4 Track 8 Knob 3"},
                {pattern="BB 4D xx", name="Factory 4 Track 1 Fader 1"},
                {pattern="BB 4E xx", name="Factory 4 Track 2 Fader 1"},
                {pattern="BB 4F xx", name="Factory 4 Track 3 Fader 1"},
                {pattern="BB 50 xx", name="Factory 4 Track 4 Fader 1"},
                {pattern="BB 51 xx", name="Factory 4 Track 5 Fader 1"},
                {pattern="BB 52 xx", name="Factory 4 Track 6 Fader 1"},
                {pattern="BB 53 xx", name="Factory 4 Track 7 Fader 1"},
                {pattern="BB 54 xx", name="Factory 4 Track 8 Fader 1"},
                {pattern="BC 0D xx", name="Factory 5 Track 1 Knob 1"},
                {pattern="BC 0E xx", name="Factory 5 Track 2 Knob 1"},
                {pattern="BC 0F xx", name="Factory 5 Track 3 Knob 1"},
                {pattern="BC 10 xx", name="Factory 5 Track 4 Knob 1"},
                {pattern="BC 11 xx", name="Factory 5 Track 5 Knob 1"},
                {pattern="BC 12 xx", name="Factory 5 Track 6 Knob 1"},
                {pattern="BC 13 xx", name="Factory 5 Track 7 Knob 1"},
                {pattern="BC 14 xx", name="Factory 5 Track 8 Knob 1"},
                {pattern="BC 1D xx", name="Factory 5 Track 1 Knob 2"},
                {pattern="BC 1E xx", name="Factory 5 Track 2 Knob 2"},
                {pattern="BC 1F xx", name="Factory 5 Track 3 Knob 2"},
                {pattern="BC 20 xx", name="Factory 5 Track 4 Knob 2"},
                {pattern="BC 21 xx", name="Factory 5 Track 5 Knob 2"},
                {pattern="BC 22 xx", name="Factory 5 Track 6 Knob 2"},
                {pattern="BC 23 xx", name="Factory 5 Track 7 Knob 2"},
                {pattern="BC 24 xx", name="Factory 5 Track 8 Knob 2"},
                {pattern="BC 31 xx", name="Factory 5 Track 1 Knob 3"},
                {pattern="BC 32 xx", name="Factory 5 Track 2 Knob 3"},
                {pattern="BC 33 xx", name="Factory 5 Track 3 Knob 3"},
                {pattern="BC 34 xx", name="Factory 5 Track 4 Knob 3"},
                {pattern="BC 35 xx", name="Factory 5 Track 5 Knob 3"},
                {pattern="BC 36 xx", name="Factory 5 Track 6 Knob 3"},
                {pattern="BC 37 xx", name="Factory 5 Track 7 Knob 3"},
                {pattern="BC 38 xx", name="Factory 5 Track 8 Knob 3"},
                {pattern="BC 4D xx", name="Factory 5 Track 1 Fader 1"},
                {pattern="BC 4E xx", name="Factory 5 Track 2 Fader 1"},
                {pattern="BC 4F xx", name="Factory 5 Track 3 Fader 1"},
                {pattern="BC 50 xx", name="Factory 5 Track 4 Fader 1"},
                {pattern="BC 51 xx", name="Factory 5 Track 5 Fader 1"},
                {pattern="BC 52 xx", name="Factory 5 Track 6 Fader 1"},
                {pattern="BC 53 xx", name="Factory 5 Track 7 Fader 1"},
                {pattern="BC 54 xx", name="Factory 5 Track 8 Fader 1"},
                {pattern="BD 0D xx", name="Factory 6 Track 1 Knob 1"},
                {pattern="BD 0E xx", name="Factory 6 Track 2 Knob 1"},
                {pattern="BD 0F xx", name="Factory 6 Track 3 Knob 1"},
                {pattern="BD 10 xx", name="Factory 6 Track 4 Knob 1"},
                {pattern="BD 11 xx", name="Factory 6 Track 5 Knob 1"},
                {pattern="BD 12 xx", name="Factory 6 Track 6 Knob 1"},
                {pattern="BD 13 xx", name="Factory 6 Track 7 Knob 1"},
                {pattern="BD 14 xx", name="Factory 6 Track 8 Knob 1"},
                {pattern="BD 1D xx", name="Factory 6 Track 1 Knob 2"},
                {pattern="BD 1E xx", name="Factory 6 Track 2 Knob 2"},
                {pattern="BD 1F xx", name="Factory 6 Track 3 Knob 2"},
                {pattern="BD 20 xx", name="Factory 6 Track 4 Knob 2"},
                {pattern="BD 21 xx", name="Factory 6 Track 5 Knob 2"},
                {pattern="BD 22 xx", name="Factory 6 Track 6 Knob 2"},
                {pattern="BD 23 xx", name="Factory 6 Track 7 Knob 2"},
                {pattern="BD 24 xx", name="Factory 6 Track 8 Knob 2"},
                {pattern="BD 31 xx", name="Factory 6 Track 1 Knob 3"},
                {pattern="BD 32 xx", name="Factory 6 Track 2 Knob 3"},
                {pattern="BD 33 xx", name="Factory 6 Track 3 Knob 3"},
                {pattern="BD 34 xx", name="Factory 6 Track 4 Knob 3"},
                {pattern="BD 35 xx", name="Factory 6 Track 5 Knob 3"},
                {pattern="BD 36 xx", name="Factory 6 Track 6 Knob 3"},
                {pattern="BD 37 xx", name="Factory 6 Track 7 Knob 3"},
                {pattern="BD 38 xx", name="Factory 6 Track 8 Knob 3"},
                {pattern="BD 4D xx", name="Factory 6 Track 1 Fader 1"},
                {pattern="BD 4E xx", name="Factory 6 Track 2 Fader 1"},
                {pattern="BD 4F xx", name="Factory 6 Track 3 Fader 1"},
                {pattern="BD 50 xx", name="Factory 6 Track 4 Fader 1"},
                {pattern="BD 51 xx", name="Factory 6 Track 5 Fader 1"},
                {pattern="BD 52 xx", name="Factory 6 Track 6 Fader 1"},
                {pattern="BD 53 xx", name="Factory 6 Track 7 Fader 1"},
                {pattern="BD 54 xx", name="Factory 6 Track 8 Fader 1"},
                {pattern="BE 0D xx", name="Factory 7 Track 1 Knob 1"},
                {pattern="BE 0E xx", name="Factory 7 Track 2 Knob 1"},
                {pattern="BE 0F xx", name="Factory 7 Track 3 Knob 1"},
                {pattern="BE 10 xx", name="Factory 7 Track 4 Knob 1"},
                {pattern="BE 11 xx", name="Factory 7 Track 5 Knob 1"},
                {pattern="BE 12 xx", name="Factory 7 Track 6 Knob 1"},
                {pattern="BE 13 xx", name="Factory 7 Track 7 Knob 1"},
                {pattern="BE 14 xx", name="Factory 7 Track 8 Knob 1"},
                {pattern="BE 1D xx", name="Factory 7 Track 1 Knob 2"},
                {pattern="BE 1E xx", name="Factory 7 Track 2 Knob 2"},
                {pattern="BE 1F xx", name="Factory 7 Track 3 Knob 2"},
                {pattern="BE 20 xx", name="Factory 7 Track 4 Knob 2"},
                {pattern="BE 21 xx", name="Factory 7 Track 5 Knob 2"},
                {pattern="BE 22 xx", name="Factory 7 Track 6 Knob 2"},
                {pattern="BE 23 xx", name="Factory 7 Track 7 Knob 2"},
                {pattern="BE 24 xx", name="Factory 7 Track 8 Knob 2"},
                {pattern="BE 31 xx", name="Factory 7 Track 1 Knob 3"},
                {pattern="BE 32 xx", name="Factory 7 Track 2 Knob 3"},
                {pattern="BE 33 xx", name="Factory 7 Track 3 Knob 3"},
                {pattern="BE 34 xx", name="Factory 7 Track 4 Knob 3"},
                {pattern="BE 35 xx", name="Factory 7 Track 5 Knob 3"},
                {pattern="BE 36 xx", name="Factory 7 Track 6 Knob 3"},
                {pattern="BE 37 xx", name="Factory 7 Track 7 Knob 3"},
                {pattern="BE 38 xx", name="Factory 7 Track 8 Knob 3"},
                {pattern="BE 4D xx", name="Factory 7 Track 1 Fader 1"},
                {pattern="BE 4E xx", name="Factory 7 Track 2 Fader 1"},
                {pattern="BE 4F xx", name="Factory 7 Track 3 Fader 1"},
                {pattern="BE 50 xx", name="Factory 7 Track 4 Fader 1"},
                {pattern="BE 51 xx", name="Factory 7 Track 5 Fader 1"},
                {pattern="BE 52 xx", name="Factory 7 Track 6 Fader 1"},
                {pattern="BE 53 xx", name="Factory 7 Track 7 Fader 1"},
                {pattern="BE 54 xx", name="Factory 7 Track 8 Fader 1"},
                {pattern="BF 0D xx", name="Factory 8 Track 1 Knob 1"},
                {pattern="BF 0E xx", name="Factory 8 Track 2 Knob 1"},
                {pattern="BF 0F xx", name="Factory 8 Track 3 Knob 1"},
                {pattern="BF 10 xx", name="Factory 8 Track 4 Knob 1"},
                {pattern="BF 11 xx", name="Factory 8 Track 5 Knob 1"},
                {pattern="BF 12 xx", name="Factory 8 Track 6 Knob 1"},
                {pattern="BF 13 xx", name="Factory 8 Track 7 Knob 1"},
                {pattern="BF 14 xx", name="Factory 8 Track 8 Knob 1"},
                {pattern="BF 1D xx", name="Factory 8 Track 1 Knob 2"},
                {pattern="BF 1E xx", name="Factory 8 Track 2 Knob 2"},
                {pattern="BF 1F xx", name="Factory 8 Track 3 Knob 2"},
                {pattern="BF 20 xx", name="Factory 8 Track 4 Knob 2"},
                {pattern="BF 21 xx", name="Factory 8 Track 5 Knob 2"},
                {pattern="BF 22 xx", name="Factory 8 Track 6 Knob 2"},
                {pattern="BF 23 xx", name="Factory 8 Track 7 Knob 2"},
                {pattern="BF 24 xx", name="Factory 8 Track 8 Knob 2"},
                {pattern="BF 31 xx", name="Factory 8 Track 1 Knob 3"},
                {pattern="BF 32 xx", name="Factory 8 Track 2 Knob 3"},
                {pattern="BF 33 xx", name="Factory 8 Track 3 Knob 3"},
                {pattern="BF 34 xx", name="Factory 8 Track 4 Knob 3"},
                {pattern="BF 35 xx", name="Factory 8 Track 5 Knob 3"},
                {pattern="BF 36 xx", name="Factory 8 Track 6 Knob 3"},
                {pattern="BF 37 xx", name="Factory 8 Track 7 Knob 3"},
                {pattern="BF 38 xx", name="Factory 8 Track 8 Knob 3"},
                {pattern="BF 4D xx", name="Factory 8 Track 1 Fader 1"},
                {pattern="BF 4E xx", name="Factory 8 Track 2 Fader 1"},
                {pattern="BF 4F xx", name="Factory 8 Track 3 Fader 1"},
                {pattern="BF 50 xx", name="Factory 8 Track 4 Fader 1"},
                {pattern="BF 51 xx", name="Factory 8 Track 5 Fader 1"},
                {pattern="BF 52 xx", name="Factory 8 Track 6 Fader 1"},
                {pattern="BF 53 xx", name="Factory 8 Track 7 Fader 1"},
                {pattern="BF 54 xx", name="Factory 8 Track 8 Fader 1"},

	}

	remote.define_auto_inputs(inputs)

	local outputs = {
	}
	remote.define_auto_outputs(outputs)

end

--[[
0 - Custom
1 - Volume
2 - Device
3 - Pan
4 - Send A
5 - Send B
]]--
g_knob_mode = 2 -- default is Device mode

--[[
0 - Custom
1 - Drum
2 - Session
]]--
g_pad_mode = 2 -- default id Session mode

--[[
Shift status 0 or 127
]]--
g_shift_status = false

function remote_probe(manufacturer, model, prober)
	-- auto detect the surface

	local results = {}
	local port_out = 0
	local ins = {}
	local received_ports = {}
	local dev_found = 0
	local request_events={}
	local response = {}
	request_events = { remote.make_midi("F0 7E 7F 06 01 F7") }
	response = "F0 7E 00 06 02 00 20 29 02 01 00 00 ?? ?? ?? ?? F7"

	local function match_events(mask,events)
		for i,event in ipairs(events) do
			local res = remote.match_midi(mask,event)
			if res ~= nil then
				return true
			end
		end
		return false
	end

	-- check all the MIDI OUT ports
	for outPortIndex = 1, prober.out_ports do
		-- send device inquiry msg
		prober.midi_send_function(outPortIndex,request_events)
		prober.wait_function(50)

		-- check all the MIDI IN ports
		for inPortIndex = 1,prober.in_ports do
			local events = prober.midi_receive_function(inPortIndex)
			if match_events(response,events) then
				port_out = outPortIndex + 1         -- DAW port
			--	table.insert(ins, inPortIndex + 1)  -- DAW port
				table.insert(ins, inPortIndex)    -- MIDI port
				dev_found = dev_found + 1
				break
			end
		end
		if dev_found ~= 0 then
			break
		end
	end

	-- check a device has been found
	if dev_found ~= 0 then
		local one_result = { in_ports={ins[1], ins[2]}, out_ports={port_out} }
		table.insert(results, one_result)
	end

	return results
end

function remote_prepare_for_use()
	-- set device to 'DAW mode' and enter SESSION layout
	local retEvents = {
		remote.make_midi("9F 0C 7F"),
		remote.make_midi("BF 03 02"), -- PAD: SESSION LAYOUT
		remote.make_midi("BF 09 02"), -- KNOBS: DEVICE LAYOUT
	}
	return retEvents
end

function remote_release_from_use()
	-- set device to 'BASIC mode'
	local retEvents = {
		remote.make_midi("BF 03 00"),
		remote.make_midi("BF 09 00"),
		remote.make_midi("9F 0C 00"),
	}
	return retEvents
end

--[[
This function is called for each incoming MIDI event.
This is where the codec interprets the message and translates it into a Remote message.
The translated message is then passed back to Remote with a call to remote.handle_input().
If the event was translated and handled this function should return true, to indicate that the event was used.
If the function returns false, Remote will try to find a match using the automatic input registry defined with remote.define_auto_inputs().
]]--
function remote_process_midi(event)
	-- BF events:
	if event[1] == 191 then
		-- set pad mode
		if event[2] == 3 then
			g_pad_mode = event[3]
			-- use this event but not handle
			return true

		-- set knob mode
		elseif event[2] == 9 then
			g_knob_mode = event[3]
			-- use this event but not handle
			return true

		-- knob handler | BF 15 - BF 1C | knobe_mode 1 <> 5
		elseif event[2] >= 21 and event[2] <= 28 and not g_shift_status then
			-- knob_index 9 <> 40
			local knob_index = g_knob_mode * 8 + event[2] - 20
			remote.handle_input({time_stamp=event.time_stamp, item=knob_index, value=event[3]})
			return true

		-- Shifted Play & Record
		elseif (event[2] == 115 or event[2] == 117) and g_shift_status then
			local button_index = 89
			if event[2] == 117 then
				button_index = 90
			end
			remote.handle_input({time_stamp=event.time_stamp, item=button_index, value=event[3]})
			return true
		end

	-- B0 events:
	elseif event[1] == 176 then
		-- set shift status
		if event[2] == 108 then
			if event[3] == 0 then
				g_shift_status = false
			else
				g_shift_status = true
			end
			return true

		-- Shifted Cliplaunch 1/2
		elseif (event[2] == 104 or event[2] == 105) and g_shift_status then
			local button_index = event[2] - 19
			remote.handle_input({time_stamp=event.time_stamp, item=button_index, value=event[3]})
			return true
		end
	end

	return false
end
